guis:
  build:
    title: "&aBuild"
    size: 9
    contents:
      0:
        material: "CHERRY_LOG"
        name: "&dCherry Set"
        lore:
          - "Receive the cherry set, which contains:"
          - "Cherry Planks"
          - "Cherry Logs"
          - "Cherry Slabs"
          - "Cherry Stairs"
        commands:
          - "ci all {player}"
          - "additem {player} 1 CHERRY_PLANKS CHERRY_LOG CHERRY_SLAB CHERRY_STAIRS"
  tools:
    title: "&bTools"
    size: 27
    contents:
      0:
        material: "DIAMOND_PICKAXE"
        name: "&bTools Set"
        lore:
          - "Receive the tools set, which contains:"
          - "Diamond Pickaxe"
        commands:
          - "ci all {player}"
          - "additem {player} 1 DIAMOND_PICKAXE DIAMOND_AXE"