# PLEASE READ
# As of right now, you can not set certain permissions individually to a player,
# they can only have the permission through the rank. Permissions for commands are as follows:
# /clearinventory - clearinv
# /additem - additem
# /setrank - setrank
# /ckick - ckick
# /cgamemode - cgamemode
# /menu - menu
# /modspec - modspec
# IF YOU TRY TO CHANGE THAT OR USE SMT ELSE IT WON'T FUNCTION PROPERLY

ranks:
  default:
    prefix: "&7[NORMIE] "
  admin:
    prefix: "&b[ADMIN] "
    permissions:
      - "all"
  moderator:
    prefix: "&d[MODERATOR] "
    permissions:
      - "clearinv"
      - "additem"
      - "setrank"
      - "ckick"
      - "cgamemode"
      - "menu"
      - "modspec"



# PLEASE READ
# As of right now, the player has to have the permission/rank to execute whatever commands are put into the commands slot
# ie if you put "additem {player} 1 STONE" and the player doesn't have the mod.additem permission, the command will not execute :D
# GUI INVENTORY SIZE MUST BE A MULTIPLE OF 9 INCREASING TO 45 MAX
# 9 18 27 36 45

guis:
  build:
    title: "&aBuild"
    size: 9
    contents:
      0:
        material: "CHERRY_LOG"
        name: "&dCherry Set"
        lore:
          - "Receive the cherry set, which contains:"
          - "Cherry Planks"
          - "Cherry Logs"
          - "Cherry Slabs"
          - "Cherry Stairs"
        commands:
          - "ci all {player}"
          - "additem {player} 1 CHERRY_PLANKS CHERRY_LOG CHERRY_SLAB CHERRY_STAIRS"
  tools:
    title: "&bTools"
    size: 27
    contents:
      0:
        material: "DIAMOND_PICKAXE"
        name: "&bTools Set"
        lore:
          - "Receive the tools set, which contains:"
          - "Diamond Pickaxe"
        commands:
          - "ci all {player}"
          - "additem {player} 1 DIAMOND_PICKAXE DIAMOND_AXE"
  options:
    title: "&4Options"
    size: 9
    contents:
      0:
        material: "STONE"
        name: "Open Build Menu"
        lore:
          - "whatever lore"
        commands:
          - "menu build"

compass:
  material: "NETHER_STAR"
  name: "&2Options"
  slot: 8
  commands:
    - "menu options"